services:
  - type: web
    name: restaurant-twa-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: BOT_TOKEN
        sync: false